### ISSUE TITLE
Desenhar o wireframe das paginas da aplicação

### ISSUE THREAD

**Issue by alissons-repos** [alissons-repos/projeto-de-front-end#2]

**Comment by alissons-repos** [comment]
Pessoal, vamos comentar aqui nossas sugestões para as páginas da nossa aplicação.
O André ficou responsável pelo desenho do wireframe e o projeto no Figma está no link abaixo.

Link projeto Figma: https://www.figma.com/file/KvDlxWmPS80nUQRDzpD2HL/Untitled?node-id=0-1&t=dp7plh1mwgia7wMB-0

**Comment by alissons-repos** [comment]
Pra mim, até então, ficou perfeito. Todas as páginas estão coerentes com aquilo que pensamos em sala.

A única coisa que senti falta foi de uma cor verde ou marrom. Podemos ir decidindo isso ao longo do desenvolvimento.

**Comment by gabrielbueno3** [comment]
Pra mim esta tudo perfeito no projeto. Minha ideia seria que no status do pet como por exemplo ''adoção'' ''cruzamento'' tenha cores especificas para cada status do pet.
